# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8880

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/personal?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Woshizhu~!@#1314
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

