server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/personal?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #  属性类型是字符串，通过别名的方式配置扩展插件，
      #  常用的插件有：
      #  监控统计用的filter:stat
      #  日志用的filter:log4j
      #  防御sql注入的filter:wall
      filters: stat,wall
      #初始化时建立物理连接的个数
      initial-size: 5
      #最大连接池数量
      max-active: 10
      #最小连接池数量
      min-idle: 2
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #有两个含义：
      #  1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      #  2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      #连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'
      validation-query: select 'x'
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keep-alive: true
      #单位：秒，检测连接是否有效的超时时间
      #validation-query-timeout: 60000
mybatis:
  check-config-location: true
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis/mybatis-config.xml